### ISSUE TITLE
Pagination and search link placement not getting top/bottom break

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-themes/default#10]
Looks like the break to top and bottom links for the pagination aren't happening around the list of item sets in the browse item sets block, at least for a simple one item set example.
![defaultpagination](https://user-images.githubusercontent.com/153262/34125050-14ff7bae-e403-11e7-8c91-c005880f7491.png)

**Comment by kimisgold** [comment]
@patrickmj Can you check that the most recent change addresses this issue?

**Comment by patrickmj** [comment]
Yep! Looks as expected.
