### ISSUE TITLE
Test single line top nav containing submenus

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/default#15]
The initial bug is documented in omeka/omeka-s#1453. The solution in the `flex-fix` branch constrains navigation to a single row on the desktop so that the hover menu is never vertically separated from its parent.

I predict users will ask about wrapping, but I'd like to think it's a reasonable request to pare the navigation down to something that works on one line...

**Comment by mebrett** [comment]
Navigation is constrained to a single row. There looks to be enough room between nav items that it should be clear which is which. 
![Screen Shot 2019-10-07 at 11 32 50 AM](https://user-images.githubusercontent.com/2314070/66325985-36c52780-e8f6-11e9-9f12-290fff50650e.png)

**Comment by zerocrates** [comment]
resolution on this?

**Comment by mebrett** [comment]
I'd say it's good to go.

**Comment by m-art-in** [comment]
Sorry, I still have the bug with 1.4.2

**Comment by kimisgold** [comment]
@mebrett Could you look at this again? Apparently there was some bottom padding no the header that broke the path between parent menu items to their child menus. The fix is on default's master branch.

**Comment by mebrett** [comment]
The fix works for me. I tested it in Chrome, Safari, and Firefox
