### ISSUE TITLE
Test new mobile menu and fix for awkward positioning when nav item is selected

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/default#17]
See forum post for details: https://forum.omeka.org/t/default-theme-navigation-bar-jumping-when-item-is-selected/10539/3

The problem was spillover behavior from mobile submenu navigation. The mobile navigation itself wasn't working, as it relied on unreliable hover behavior using a pure CSS approach. I've revised it to use jQuery generated buttons that should behave more consistently. 

This test issue is looking for the following: 

* On desktop, selecting a navigation item no longer causes the nav bar to jump left.
* Mobile navigation now uses buttons for toggling submenus open and closed. 

The fix is on the `mobile-nav-button-toggle` branch.

**Comment by mebrett** [comment]
Working as expected in mobile and desktop.
On mobile, the search is always open below the page title and menu, and above content. Is this expected behavior? 
![defaulttheme20200228](https://user-images.githubusercontent.com/2314070/75559595-bc668280-5a11-11ea-8230-15ace94c0498.jpeg)

**Comment by kimisgold** [comment]
Yup, that's expected!
