### ISSUE TITLE
Advanced search in mobile view

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-themes/default#21]
Here’s an interesting thing about the public advanced search interface. When the screen is reduced enough that the default theme switches to mobile mode, the simple search box spreads across the width of the screen. As a result, it’s easy to set the advanced search parameters and then miss that the search button is at the bottom of the form and hit the search icon for the simple search instead.

![Screenshot_2021-03-18 OTG Dev Description · On These Grounds](https://user-images.githubusercontent.com/741480/111715308-eca1de80-8829-11eb-9f5f-0c7ded6a8be7.png)

**Comment by kimisgold** [comment]
For the moment I've hidden the simple search on mobile views of the advanced search. Would this be a good solution to this scenario?

**Comment by kimisgold** [comment]
@sharonmleon This might be ready to close, but I wanted to get your thoughts on the solution I mentioned above.

**Comment by sharonmleon** [comment]
@kimisgold Seems fixed to me. When the width is really small the keyword search disappears, which totally eliminates the confusion.
