### ISSUE TITLE
jsTranslate needs Omeka object

### ISSUE THREAD

**Issue by fitnycdigitalinitiatives** [omeka-s-themes/default#29]
I noticed an error caused by this [commit 003f6e3](https://github.com/omeka-s-themes/default/commit/003f6e354b53dbb9d3c20f9f0e43d572db5a7798). It causes jsTranslate to break, "Uncaught ReferenceError: Omeka is not defined."

**Comment by zerocrates** [comment]
Can you confirm which version of Omeka S you're using when you see this error?

**Comment by fitnycdigitalinitiatives** [comment]
:facepalm: yep, I was definitely using the latest version of this theme with an older version of omeka—my apologies!
