### ISSUE TITLE
Test banner setting

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/default#30]
There is now a theme setting that allows users to select a banner image to appear across site views. In additional settings, they can control:

* the maximum height of the banner for both mobile and desktop widths
* where to position the image within the banner container when the container ratio has a much greater width than height

Note: we're testing this setting across a bunch of themes, and I decided to omit the contained width setting for Default, as it doesn't really fit the look of this theme.

This is on the `master` branch and should be tested on desktop and mobile browsers.

**Comment by katknow** [comment]
This works really well across desktop browsers. The only thing is that the search bar does sit on top right corner of the banner when fixed to top--I think it looks fine, but I don't know if it would matter to some folks/with specific banner images. While I can get the banner to appear and work fine on my iPhone, I cannot get it to appear under any circumstances using the Chrome developer tools so I wonder if there might be issues on other mobile devices.

**Comment by kimisgold** [comment]
I think the issue might have something to do with a margin style applying to mobile styles when it shouldn't. [I've just pushed a fix](https://github.com/omeka-s-themes/default/commit/2a0c16267361a27f9e98c75f58311ef20a2b2873) that should be ready to test.

**Comment by katknow** [comment]
That fixed it in terms of showing up in the developer tools! This one also isn't following the selection for where to fix the banner, but while the other two had issues of fixing to the top this one seems to stay fixed on center on mobile.

**Comment by katknow** [comment]
Re-checked on mobile, seems good to go!
