### ISSUE TITLE
Banner & Logo Behavior

### ISSUE THREAD

**Issue by spswanz** [omeka-s-themes/default#31]
Is this expected behavior?

When I add an **logo** in the theme settings, the site Title does not display:
<img width="969" alt="Screen Shot 2022-01-09 at 6 31 20 PM" src="https://user-images.githubusercontent.com/6654596/148707428-240ffa59-2d83-47b8-9b74-405ce7b3b834.png">
Looking at the HTML, it seems the site title is given as the logo alt-text, but does not render on the page.

When I add a **banner** instead (no logo), I get the site title and the nav bar, but above the banner. I'd expect the title & nav to be below the banner (like it is for logo).  
<img width="1248" alt="Screen Shot 2022-01-09 at 6 35 41 PM" src="https://user-images.githubusercontent.com/6654596/148707640-0583dbae-6cec-4596-932f-9ce6f15a40f3.png">

Thanks

**Comment by kimisgold** [comment]
Yes this is expected behavior. Often logo graphics will be a wordmark that renders the site title redundant. The banner is more a presentation element. We placed the site title and navigation above it as they are key functional elements that shouldn't get buried under a decorative image.
