### ISSUE TITLE
Regions

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/default#40]
Default is only offering a "Main" region on item sets, but on the public page everything is displaying in, like, a right sidebar.

<img width="644" alt="Screenshot 2024-05-14 at 12 54 29" src="https://github.com/omeka-s-themes/default/assets/28012148/edfb7d19-da2e-4698-b3ec-a52d6558fd02">
<img width="1197" alt="Screenshot 2024-05-14 at 12 54 45" src="https://github.com/omeka-s-themes/default/assets/28012148/8de007fb-4fdc-4e15-a87f-c78975ab4f05">

**Comment by kimisgold** [comment]
I've fixed those styles. The item set's content will still appear as a (wider) sidebar, because I've found users tend to populate item set metadata fairly sparsely while focusing on the items belong to it.

**Comment by allanaaa** [comment]
Thanks - items sets are better, though the gray vertical bar is a bit unnecessary now. I wouldn't call it "Main" as a region - is there any way to represent the item set's contents on the admin side? Not to move it around, but just to show where it will appear relative to the regions you're offered?

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-second-omeka-s-site/item-set/4255

<img width="1582" alt="Screenshot 2024-05-27 at 13 07 45" src="https://github.com/omeka-s-themes/default/assets/28012148/bfef9ebb-949d-4b0c-bc85-22f37f24d2c5">

**Comment by allanaaa** [comment]
Item pages offer a right sidebar that is also not displaying.

<img width="725" alt="Screenshot 2024-05-27 at 13 08 53" src="https://github.com/omeka-s-themes/default/assets/28012148/7e9937e1-262c-41de-b583-ec2cde2296be">

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-second-omeka-s-site/item/10005#lg=1&slide=0

**Comment by kimisgold** [comment]
The right sidebar has been removed, as default is meant to use the views provided by the Omeka S core. Providing a right sidebar would require a custom view, and it was likely initially included by accident when implementing configurable regions across themes.

Regarding item set "main", it's the main region pertaining specifically to the item sets. I know the items with the set take up more visual space, but I'm not sure it's enough confusion to warrant having it break from the pattern of the other primary configurable regions in items and media.

> is there any way to represent the item set's contents on the admin side? Not to move it around, but just to show where it will appear relative to the regions you're offered?

I don't think so at this time, but it could be worth discussing as a feature request.
