### ISSUE TITLE
Little to no bottom margin for prev/next navigation links 

### ISSUE THREAD

**Issue by alyssafahringer** [omeka-s-themes/default#5]
Not sure if this is an issue, but there isn't much room on the bottom margin of the prev | next links at the bottom of the page. 

![screen shot 2016-10-24 at 3 11 38 pm](https://cloud.githubusercontent.com/assets/8807816/19660016/3b8cda7a-99fc-11e6-8045-021e0ee51e73.png)

**Comment by jannellelegg** [comment]
Additionally, the "Submit" button for Collecting is populating very close to the prev | next links at the bottom of the page.

![screen shot 2016-10-25 at 10 48 10 am](https://cloud.githubusercontent.com/assets/5897725/19691032/c83509e4-9aa0-11e6-9f1a-5f7566e817ab.png)

This might be a separate issue, but this [Collecting page](http://dev.omeka.org/mebrett/testomekas/s/FlicksOfThe80s/page/submissions) should be the last page in the navigation - rendering the "Next" button unclickable.
