### ISSUE TITLE
Title sizing

### ISSUE THREAD

**Issue by jannellelegg** [omeka-s-themes/default#7]
The text size for item titles seems to differ, based on the number of images per row. 

Demo page has multiple showcases, some with more items than others. All of these showcases are set for "Large" thumbnail sizes. These are standardized in rows with two or more images.  The text size for item titles is also different based on number of images per row- one image in a row is large, two or more are all the same size.

![screen shot 2016-10-25 at 1 08 39 pm](https://cloud.githubusercontent.com/assets/5897725/19696281/70db3d4e-9ab4-11e6-8d0f-d35e09fd4178.png)

The result is that showcases with one image have a title font size that is significantly larger than the font used in any of the other showcases.

**Comment by kimisgold** [comment]
The intent here is that a single item takes up more visual space in a showcase block than multiple items in a showcase block. The heading and image sizes gets bumped down with multiple items.
